// Catálogo da loja — alimenta o gerador estático (cards do catálogo + página de vendas de cada produto).
// Campos marcados "html ok" no schema aceitam <em> e <strong>.
// Regra: valores de entregáveis + bônus (com valor) somam precoDe.

const IMG_NV = 'assets/img/produtos/nervo-vago/';
const IMG_BC = 'assets/img/produtos/baralho-constelacao/';
const IMG_RC = 'assets/img/produtos/radiestesia-cigana/';

// Respostas de FAQ que se repetem em todos os produtos
const faqRecebimento = {
  p: 'Quando e como recebo o material?',
  r: 'Logo após a confirmação do pagamento, você recebe no seu e-mail o link de acesso. No Pix e no cartão, a liberação costuma ser imediata. Se o e-mail não aparecer em alguns minutos, confira as abas <strong>Spam</strong> e <strong>Promoções</strong>. Não encontrou? Chame o nosso suporte pelo WhatsApp ou e-mail indicados nesta página — uma pessoa da equipe resolve para você.',
};
const faqVitalicio = {
  p: 'O acesso é vitalício?',
  r: 'Sim. O pagamento é único, sem mensalidade. Você pode baixar todos os arquivos, guardar no seu computador ou na nuvem e usar sempre que precisar.',
};

export default [
  // ─────────────────────────────────────────────────────────────
  // 1) NERVO VAGO
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'nervo-vago',
    nome: 'Kit Regulação do Sistema Nervoso',
    nomeCurto: 'Nervo Vago',
    categoria: 'Regulação Emocional',
    cor: 'teal',
    selo: '+120 ferramentas',
    resumo: 'Mais de 120 ferramentas prontas, baseadas na Teoria Polivagal, para regular o sistema nervoso dos seus pacientes dentro e fora da sessão.',
    publico: ['Psicólogas', 'Terapeutas', 'Psicanalistas', 'Terapeutas holísticas', 'Coaches'],
    preco: 37,
    precoDe: 368,
    parcelas: '5x de R$ 8,31',
    checkout: 'https://lastlink.com/p/C9E7D1905/checkout-payment/',
    garantiaDias: 30,
    imagemCapa: IMG_NV + 'hero-baralho.webp',
    galeria: [
      IMG_NV + 'mockup-1.webp',
      IMG_NV + 'mockup-2.webp',
      IMG_NV + 'mockup-3.webp',
      IMG_NV + 'mockup-4.webp',
      IMG_NV + 'carta-01.webp',
      IMG_NV + 'carta-02.webp',
      IMG_NV + 'carta-03.webp',
      IMG_NV + 'carta-04.webp',
    ],
    seo: {
      title: 'Kit Regulação do Sistema Nervoso — +120 Ferramentas do Nervo Vago',
      description: 'Mais de 120 ferramentas prontas, baseadas na Teoria Polivagal, para regular o sistema nervoso dos pacientes. PDF com acesso imediato.',
    },
    hero: {
      eyebrow: 'Teoria Polivagal na prática clínica',
      titulo: '+120 ferramentas prontas para <em>regular</em> o sistema nervoso dos seus pacientes',
      subtitulo: 'Cartas, guias e exercícios baseados na Teoria Polivagal para você conduzir a sessão com segurança, <strong>sem improvisar</strong>. Material organizado para usar já no próximo atendimento, presencial ou online.',
      bullets: [
        'Acesso imediato por e-mail',
        'PDF pronto para imprimir ou usar na tela',
        'Funciona no presencial e no online',
        'Suporte humano pelo WhatsApp',
      ],
    },
    problema: {
      titulo: 'Sua paciente <em>entende tudo</em> — e continua ansiosa',
      paragrafos: [
        'Ela já sabe de onde vem a ansiedade. Já nomeou os gatilhos, já entendeu a história. Mesmo assim, o coração dispara, o corpo trava e a crise volta na semana seguinte.',
        'Isso acontece porque ansiedade e trauma não começam na mente. Começam no sistema nervoso. Enquanto o corpo continua em estado de alerta, a compreensão racional sozinha não é suficiente para trazer calma.',
        'E, na hora da sessão, nem sempre há tempo de montar uma intervenção corporal do zero. A terapeuta acaba improvisando ou voltando para a conversa.',
      ],
      dores: [
        'Pacientes que entendem o problema, mas não conseguem se acalmar',
        'Crises emocionais em sessão sem um recurso rápido à mão',
        'Pouco material prático de Teoria Polivagal em português',
        'Horas preparando exercícios que poderiam estar prontos',
        'Dificuldade de manter o trabalho vivo entre uma sessão e outra',
      ],
    },
    solucao: {
      titulo: 'Um kit para trabalhar <em>com o corpo</em>, não só com a mente',
      texto: 'O Kit Regulação do Sistema Nervoso reúne mais de 120 ferramentas baseadas na Teoria Polivagal e na terapia somática: baralhos terapêuticos, guias teóricos, cadernos de exercícios e fichas de acompanhamento. Tudo organizado para você identificar o estado do sistema nervoso da paciente e escolher a intervenção certa em poucos minutos.',
      pontos: [
        { titulo: 'Base científica clara', texto: 'Fundamentado na Teoria Polivagal, explicado de forma aplicável à clínica.' },
        { titulo: 'Intervenções rápidas', texto: 'Exercícios de 5 a 10 minutos para usar no meio da sessão, quando a paciente precisa.' },
        { titulo: 'Psicoeducação pronta', texto: 'Materiais que ajudam a paciente a entender o próprio sistema nervoso.' },
        { titulo: 'Continuidade entre sessões', texto: 'Atividades para a paciente praticar em casa e chegar mais regulada ao próximo encontro.' },
      ],
    },
    entregaveis: [
      { nome: 'Baralho Nervo Vago — 64 Cartas Terapêuticas', descricao: 'Cartas com práticas de regulação para usar em sessão ou indicar para casa.', valor: 47, imagem: IMG_NV + 'hero-baralho.webp' },
      { nome: 'Cartas Corpo, Coração e Mente (+40 cartas)', descricao: 'Perguntas e práticas que integram sensação corporal, emoção e pensamento.', valor: 37, imagem: IMG_NV + 'mockup-2.webp' },
      { nome: 'Cartas de Inteligência Epigenética (+40 cartas)', descricao: 'Reflexões sobre hábitos, ambiente e padrões aprendidos que influenciam a saúde emocional.', valor: 37, imagem: IMG_NV + 'mockup-3.webp' },
      { nome: 'Cartas de Aterramento', descricao: 'Práticas curtas para trazer a paciente de volta ao presente em momentos de desregulação.', valor: 27, imagem: IMG_NV + 'mockup-4.webp' },
      { nome: 'Guia da Teoria Polivagal', descricao: 'Os conceitos essenciais explicados de forma clara e aplicável ao atendimento.', valor: 37, imagem: IMG_NV + 'mockup-5.webp' },
      { nome: 'Guia de Terapia Somática', descricao: 'Fundamentos e práticas para incluir o corpo no processo terapêutico com segurança.', valor: 27, imagem: IMG_NV + 'mockup-6.webp' },
      { nome: 'Caderno de Exercícios — Acalmar o Sistema Nervoso em Menos de 10 Minutos', descricao: 'Exercícios rápidos e guiados para usar em sessão ou como tarefa de casa.', valor: 27, imagem: IMG_NV + 'mockup-7.webp' },
      { nome: 'Atividade Entenda Seu Sistema Nervoso (+58 páginas)', descricao: 'Material de psicoeducação para a paciente compreender as próprias reações.', valor: 27, imagem: IMG_NV + 'mockup-8.webp' },
    ],
    bonus: [
      { nome: 'Protocolo de Regulação Vagal em 5 Minutos', descricao: 'Sequência curta e objetiva para momentos de crise ou início de sessão.', valor: 17, imagem: '' },
      { nome: 'Mapa dos Estados do Sistema Nervoso', descricao: 'Guia visual dos estados ventral, simpático e dorsal para identificar onde a paciente está.', valor: 17, imagem: '' },
      { nome: 'Checklist de Preparação Energética para Terapeutas', descricao: 'Rotina breve para você chegar centrada e disponível ao atendimento.', valor: 17, imagem: '' },
      { nome: 'Ficha de Acompanhamento do Paciente', descricao: 'Registro simples da evolução da regulação ao longo das sessões.', valor: 17, imagem: '' },
      { nome: 'Guia de Aplicação por Condição', descricao: 'Quais ferramentas usar em casos de ansiedade, trauma, burnout e pânico.', valor: 17, imagem: '' },
      { nome: 'Roteiro de Sessão Somática', descricao: 'Estrutura de sessão do acolhimento ao fechamento, com foco no corpo.', valor: 17, imagem: '' },
      { nome: 'Atualizações Futuras Gratuitas', descricao: 'Novos materiais adicionados ao kit chegam para você sem custo extra.', valor: 0, imagem: '' },
    ],
    comoFunciona: [
      'Você finaliza a compra em ambiente seguro (Pix, cartão ou boleto).',
      'Recebe no e-mail o acesso a todos os arquivos em PDF.',
      'Baixa, imprime ou usa direto na tela do computador, tablet ou celular.',
      'Consulta o Guia de Aplicação por Condição para escolher a ferramenta.',
      'Aplica na próxima sessão e indica exercícios para a paciente fazer em casa.',
    ],
    paraQuem: [
      'Psicólogas que atendem ansiedade generalizada, pânico e estresse crônico',
      'Terapeutas que acompanham pessoas com histórico de trauma',
      'Profissionais que querem intervenções rápidas para crises em sessão',
      'Quem atende online e precisa de recursos fáceis de compartilhar na tela',
      'Terapeutas que desejam fortalecer a psicoeducação e os exercícios entre sessões',
      'Profissionais que também buscam práticas de autocuidado e regulação para si',
    ],
    naoEPara: [
      'Quem busca substituir acompanhamento médico ou psiquiátrico',
      'Quem espera uma formação completa em Teoria Polivagal (este é um material de apoio prático)',
      'Quem prefere receber material físico pelo correio',
    ],
    faq: [
      { p: 'O material é físico ou digital?', r: '100% digital, em PDF. Você pode imprimir em casa ou numa gráfica, ou usar direto na tela do computador, tablet ou celular.' },
      faqRecebimento,
      faqVitalicio,
      { p: 'Posso usar em atendimento online e presencial?', r: 'Sim. No presencial, use as cartas impressas. No online, basta compartilhar a tela ou enviar o exercício para a paciente.' },
      { p: 'Preciso ter formação em Teoria Polivagal?', r: 'Não. O Guia da Teoria Polivagal e o Guia de Terapia Somática explicam os fundamentos de forma clara. O kit é um apoio para a sua prática e <strong>não substitui</strong> sua formação profissional nem o tratamento médico quando indicado.' },
      { p: 'Serve para quem não é psicóloga?', r: 'Sim. Terapeutas, psicanalistas, terapeutas holísticas e coaches também usam o material, sempre dentro do seu escopo de atuação.' },
      { p: 'Posso usar para mim mesma?', r: 'Pode. Muitas ferramentas funcionam como autocuidado e regulação para a própria terapeuta.' },
      { p: 'E se eu não gostar?', r: 'Você tem <strong>30 dias de garantia</strong>. Se o material não fizer sentido para você, basta pedir o reembolso ao suporte e devolvemos 100% do valor, sem burocracia.' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 2) ARTETERAPIA JUNGUIANA
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'arteterapia-junguiana',
    nome: '+120 Atividades de Arteterapia Junguiana — O Guia Prático para Profissionais',
    nomeCurto: 'Arteterapia Junguiana',
    categoria: 'Arteterapia',
    cor: 'roxo',
    selo: '+120 atividades',
    resumo: 'Mais de 120 atividades de arteterapia junguiana com objetivo, materiais, passo a passo e leitura simbólica. Não é preciso saber desenhar.',
    publico: ['Psicólogas', 'Arteterapeutas', 'Terapeutas holísticas', 'Psicopedagogas'],
    preco: 37,
    precoDe: 351,
    parcelas: '5x de R$ 8,19',
    checkout: '',
    garantiaDias: 30,
    imagemCapa: '',
    galeria: [],
    seo: {
      title: '+120 Atividades de Arteterapia Junguiana — Guia Prático para Profissionais',
      description: 'Mandalas, colagem, arquétipos, sombra e jornada do herói: +120 atividades com passo a passo e leitura simbólica. Não precisa saber desenhar.',
    },
    hero: {
      eyebrow: 'Jung e arte na sua próxima sessão',
      titulo: '+120 atividades de arteterapia junguiana para acessar o que a <em>conversa</em> não alcança',
      subtitulo: 'Mandalas, colagens, arquétipos, sombra e jornada do herói, cada atividade com objetivo, materiais, passo a passo e leitura simbólica. <strong>Você não precisa saber desenhar</strong> — e seu cliente também não.',
      bullets: [
        'Acesso imediato por e-mail',
        'PDF pronto para imprimir',
        'Materiais simples e baratos',
        'Suporte humano pelo WhatsApp',
      ],
    },
    problema: {
      titulo: 'Quando a sessão vira <em>só conversa</em>',
      paragrafos: [
        'Você conhece bem o momento: o cliente fala, racionaliza, repete a mesma história — e o processo parece girar em círculos.',
        'A conversa acessa o consciente. A arte acessa o inconsciente de forma mais direta. O que a pessoa recorta, rabisca ou pinta costuma revelar conteúdos que meses de fala não trouxeram à tona.',
        'Mas muitas profissionais não usam arte na clínica porque acham que precisam saber desenhar, fazer uma pós longa e cara, ou montar cada atividade do zero.',
      ],
      dores: [
        'Sessões que se repetem sem aprofundar',
        'Insegurança por “não saber desenhar”',
        'Falta de tempo para planejar atividades expressivas',
        'Dúvida sobre como interpretar o que o cliente produz',
        'Pós-graduação cara e demorada como única alternativa aparente',
      ],
    },
    solucao: {
      titulo: 'Abra o guia, escolha a atividade e <em>aplique</em>',
      texto: 'O guia reúne mais de 120 atividades de arteterapia junguiana organizadas em 6 categorias e por objetivo terapêutico. Cada atividade traz o objetivo, a lista de materiais, o passo a passo de condução e uma orientação de leitura simbólica, para que você saiba o que observar e como devolver ao cliente. Os recursos são acessíveis: recortes de revista, colagem, rabiscos e mandalas com contornos prontos.',
      pontos: [
        { titulo: 'Zero talento artístico', texto: 'As atividades valorizam o processo e o símbolo, não a técnica de desenho.' },
        { titulo: 'Leitura simbólica incluída', texto: 'Cada atividade traz orientações para interpretar o material à luz de Jung.' },
        { titulo: 'Sessões completas prontas', texto: '10 protocolos montados do acolhimento ao fechamento.' },
        { titulo: 'Materiais baratos', texto: 'Papel, revista, cola, lápis de cor: nada que exija ateliê.' },
      ],
    },
    entregaveis: [
      { nome: 'Caderno de Mandalas Junguianas', descricao: 'Atividades com mandalas de contorno pronto para centramento, integração e expressão do Self.', valor: 37, imagem: '' },
      { nome: 'Caderno de Colagem Intuitiva', descricao: 'Propostas com recortes de revista para acessar imagens internas sem precisar desenhar.', valor: 27, imagem: '' },
      { nome: 'Caderno de Desenho de Arquétipos', descricao: 'Atividades para reconhecer e dialogar com os arquétipos que atuam na vida do cliente.', valor: 27, imagem: '' },
      { nome: 'Caderno de Exercícios de Sombra', descricao: 'Propostas cuidadosas para olhar aspectos rejeitados da personalidade com segurança.', valor: 37, imagem: '' },
      { nome: 'Caderno da Jornada do Herói', descricao: 'Atividades que ajudam o cliente a narrar e ressignificar a própria trajetória.', valor: 27, imagem: '' },
      { nome: 'Caderno de Expressão Emocional', descricao: 'Recursos para dar forma a emoções difíceis de nomear.', valor: 27, imagem: '' },
      { nome: 'Guia de Leitura Simbólica', descricao: 'Como observar cores, formas, posição e símbolos, e devolver ao cliente sem interpretar de forma rígida.', valor: 37, imagem: '' },
      { nome: '10 Protocolos de Sessão Completa', descricao: 'Sessões montadas do início ao fim, com tempo estimado para cada etapa.', valor: 47, imagem: '' },
      { nome: 'Lista de Materiais Baratos', descricao: 'Tudo o que você precisa para começar, com alternativas econômicas.', valor: 17, imagem: '' },
    ],
    bonus: [
      { nome: 'Fichas de Registro de Sessão', descricao: 'Modelo para anotar a atividade, as produções e as observações simbólicas de cada encontro.', valor: 17, imagem: '' },
      { nome: 'Glossário de Símbolos Junguianos', descricao: 'Referência rápida dos símbolos e conceitos junguianos mais frequentes.', valor: 17, imagem: '' },
      { nome: 'Roteiro de Primeira Sessão com Arte', descricao: 'Como apresentar a arteterapia ao cliente e quebrar a resistência do “não sei desenhar”.', valor: 17, imagem: '' },
      { nome: 'Guia de Adaptação para Atendimento Online', descricao: 'Como conduzir as atividades à distância, com materiais que o cliente já tem em casa.', valor: 17, imagem: '' },
    ],
    comoFunciona: [
      'Você finaliza a compra em ambiente seguro.',
      'Recebe no e-mail o acesso a todos os cadernos em PDF.',
      'Escolhe a atividade pelo objetivo terapêutico da sessão.',
      'Separa os materiais simples indicados na atividade.',
      'Conduz pelo passo a passo e usa a leitura simbólica para o fechamento.',
    ],
    paraQuem: [
      'Psicólogas que querem incluir recursos expressivos na abordagem junguiana',
      'Arteterapeutas que buscam variedade de atividades prontas e organizadas',
      'Terapeutas holísticas que desejam aprofundar o trabalho simbólico',
      'Profissionais que “não sabem desenhar” e evitavam usar arte por isso',
      'Quem atende clientes que racionalizam muito e têm dificuldade de acessar emoções',
      'Profissionais que atendem online e presencialmente',
    ],
    naoEPara: [
      'Quem procura uma formação ou certificação em arteterapia',
      'Quem busca substituir acompanhamento psicológico ou psiquiátrico',
      'Quem prefere receber material físico pelo correio',
    ],
    faq: [
      { p: 'O material é físico ou digital?', r: '100% digital, em PDF. Você pode imprimir ou usar direto na tela do computador ou tablet.' },
      faqRecebimento,
      faqVitalicio,
      { p: 'Preciso saber desenhar?', r: 'Não. As atividades usam colagem, recortes, rabiscos e mandalas com contornos prontos. O foco é o processo simbólico, não a habilidade artística — nem sua, nem do cliente.' },
      { p: 'Preciso ter formação em arteterapia ou em Jung?', r: 'Não é obrigatório. O Guia de Leitura Simbólica e o Glossário ajudam você a conduzir com segurança. O material é um apoio prático e deve ser usado dentro do seu escopo profissional; ele <strong>não substitui</strong> uma formação na área.' },
      { p: 'Funciona no atendimento online?', r: 'Sim. Há um guia específico de adaptação para o online, com atividades que usam materiais que o cliente já tem em casa.' },
      { p: 'Os materiais são caros?', r: 'Não. Você vai usar papel, revistas, cola, tesoura e lápis de cor. A Lista de Materiais Baratos traz alternativas econômicas para tudo.' },
      { p: 'E se eu não gostar?', r: 'Você tem <strong>30 dias de garantia</strong>. Basta pedir o reembolso ao suporte e devolvemos 100% do valor.' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 3) ARTETERAPIA NA DEPENDÊNCIA QUÍMICA
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'arteterapia-dependencia-quimica',
    nome: 'Kit Arteterapia na Dependência Química',
    nomeCurto: 'Dependência Química',
    categoria: 'Arteterapia',
    cor: 'coral',
    selo: 'Individual e em grupo',
    resumo: 'Atividades de arteterapia prontas para quem atende dependência química, com dinâmicas individuais e em grupo e protocolos por fase do tratamento.',
    publico: ['Psicólogas', 'Arteterapeutas', 'Terapeutas ocupacionais', 'Equipes de CAPS AD', 'Comunidades terapêuticas'],
    preco: 37,
    precoDe: 371,
    parcelas: '5x de R$ 8,19',
    checkout: '',
    garantiaDias: 30,
    imagemCapa: '',
    galeria: [],
    seo: {
      title: 'Kit Arteterapia na Dependência Química — Atividades Prontas',
      description: 'Atividades de arteterapia para dependência química: motivação, fissura, culpa, família e prevenção de recaída. Individual e em grupo. PDF.',
    },
    hero: {
      eyebrow: 'Para clínicas, CAPS AD, comunidades e consultório',
      titulo: 'Atividades de arteterapia prontas para quem atende <em>dependência química</em>',
      subtitulo: 'Dinâmicas individuais e em grupo para trabalhar motivação, fissura, culpa, vínculos familiares e prevenção de recaída. Um recurso <strong>complementar</strong> ao trabalho da equipe, organizado por fase do tratamento.',
      bullets: [
        'Acesso imediato por e-mail',
        'PDF pronto para imprimir',
        'Atividades individuais e em grupo',
        'Suporte humano pelo WhatsApp',
      ],
    },
    problema: {
      titulo: 'Quando falar sobre o uso <em>não é suficiente</em>',
      paragrafos: [
        'Quem atende dependência química conhece a resistência: o paciente minimiza, repete o discurso que acha que a equipe quer ouvir ou simplesmente se cala.',
        'Vergonha, culpa e ambivalência dificultam que ele fale do que sente. A arte oferece outro caminho: dar forma ao que ainda não tem palavras, com menos defesa.',
        'O desafio é ter atividades adequadas a esse público, que funcionem em grupo e respeitem cada fase do tratamento — sem precisar criar tudo do zero toda semana.',
      ],
      dores: [
        'Pacientes resistentes, desconfiados ou pouco engajados',
        'Grupos terapêuticos que ficam repetitivos',
        'Pouco material de arteterapia específico para dependência química',
        'Dificuldade de trabalhar vergonha e culpa sem expor o paciente',
        'Tempo curto para planejar oficinas para turmas grandes',
      ],
    },
    solucao: {
      titulo: 'Um kit pensado para o <em>caminho da recuperação</em>',
      texto: 'O Kit Arteterapia na Dependência Química reúne cadernos temáticos de atividades expressivas voltadas às principais questões do tratamento: motivação para mudança, gatilhos e fissura, vergonha e culpa, reconstrução da identidade, vínculos familiares, prevenção de recaída e projeto de vida. Cada atividade traz objetivo, materiais, passo a passo e perguntas de fechamento, com versões para atendimento individual e em grupo.',
      pontos: [
        { titulo: 'Individual e em grupo', texto: 'Dinâmicas adaptadas para consultório, oficinas e grupos terapêuticos.' },
        { titulo: 'Organizado por fase', texto: 'Protocolos para acolhimento, tratamento, manutenção e pós-alta.' },
        { titulo: 'Linguagem acessível', texto: 'Não é preciso saber desenhar; as propostas valorizam o processo, não a técnica.' },
        { titulo: 'Complementar à equipe', texto: 'Feito para somar ao plano terapêutico multiprofissional, não para substituí-lo.' },
      ],
    },
    entregaveis: [
      { nome: 'Caderno Motivação para Mudança', descricao: 'Atividades para trabalhar a ambivalência e fortalecer o desejo de mudar.', valor: 37, imagem: '' },
      { nome: 'Caderno Gatilhos e Fissura', descricao: 'Propostas para mapear situações de risco e dar forma à fissura com mais consciência.', valor: 37, imagem: '' },
      { nome: 'Caderno Vergonha e Culpa', descricao: 'Atividades cuidadosas para acolher sentimentos difíceis sem expor o paciente.', valor: 27, imagem: '' },
      { nome: 'Caderno Reconstrução da Identidade', descricao: 'Recursos para o paciente se reconhecer para além do uso da substância.', valor: 27, imagem: '' },
      { nome: 'Caderno Vínculos Familiares', descricao: 'Atividades para olhar relações, rupturas e possibilidades de reaproximação.', valor: 27, imagem: '' },
      { nome: 'Caderno Prevenção de Recaída', descricao: 'Propostas para construir estratégias de enfrentamento e rede de apoio.', valor: 37, imagem: '' },
      { nome: 'Caderno Projeto de Vida', descricao: 'Atividades para planejar objetivos, rotina e sentido após o tratamento.', valor: 27, imagem: '' },
      { nome: 'Dinâmicas de Arteterapia em Grupo', descricao: 'Oficinas prontas para grupos terapêuticos, com tempo, materiais e condução.', valor: 47, imagem: '' },
      { nome: 'Protocolos por Fase do Tratamento', descricao: 'Sequências de atividades para acolhimento, tratamento, manutenção e pós-alta.', valor: 37, imagem: '' },
    ],
    bonus: [
      { nome: 'Fichas de Registro e Evolução', descricao: 'Modelos para registrar a participação e a evolução de cada paciente.', valor: 17, imagem: '' },
      { nome: 'Roteiro de Acolhimento com Arte', descricao: 'Como apresentar a arteterapia ao paciente e reduzir a resistência inicial.', valor: 17, imagem: '' },
      { nome: 'Atividades para Grupos de Familiares', descricao: 'Propostas para trabalhar com familiares e codependência.', valor: 17, imagem: '' },
      { nome: 'Guia de Manejo de Grupo', descricao: 'Orientações para conduzir grupos com segurança, lidar com conflitos e acolher emoções intensas.', valor: 17, imagem: '' },
    ],
    comoFunciona: [
      'Você finaliza a compra em ambiente seguro.',
      'Recebe no e-mail o acesso a todos os cadernos em PDF.',
      'Escolhe o protocolo de acordo com a fase do tratamento do paciente ou do grupo.',
      'Separa os materiais simples indicados e imprime as folhas de atividade.',
      'Conduz a atividade e registra a evolução nas fichas.',
    ],
    paraQuem: [
      'Psicólogas que atendem dependência química em consultório',
      'Profissionais de CAPS AD e serviços da rede de saúde mental',
      'Equipes de clínicas de recuperação e comunidades terapêuticas',
      'Arteterapeutas e terapeutas ocupacionais que conduzem oficinas e grupos',
      'Profissionais que trabalham com familiares de dependentes químicos',
      'Estudantes e estagiários que precisam de material estruturado de apoio',
    ],
    naoEPara: [
      'Quem busca um tratamento para dependência química — o material é uma ferramenta para profissionais',
      'Quem pretende usá-lo no lugar do acompanhamento médico, psiquiátrico e multiprofissional',
      'Quem procura uma formação ou certificação em arteterapia',
    ],
    faq: [
      { p: 'O material é físico ou digital?', r: '100% digital, em PDF. Você pode imprimir quantas cópias precisar para seus atendimentos e grupos.' },
      faqRecebimento,
      faqVitalicio,
      { p: 'Posso usar em grupo?', r: 'Sim. Há um caderno específico de dinâmicas em grupo e a maior parte das atividades traz orientação para uso individual e coletivo.' },
      { p: 'Funciona no atendimento online?', r: 'Sim, especialmente as atividades individuais. O paciente pode realizar com materiais simples que já tem em casa enquanto você conduz pela chamada.' },
      { p: 'Preciso ter formação em arteterapia?', r: 'Não é obrigatório. As atividades têm passo a passo detalhado. Use sempre dentro do seu escopo profissional e em articulação com a equipe responsável pelo tratamento.' },
      { p: 'O kit substitui o tratamento?', r: '<strong>Não.</strong> A arteterapia é um recurso complementar. O cuidado da dependência química exige acompanhamento médico, psicológico e multiprofissional adequado a cada caso.' },
      { p: 'E se eu não gostar?', r: 'Você tem <strong>30 dias de garantia</strong>. Basta pedir o reembolso ao suporte e devolvemos 100% do valor.' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 4) BARALHO DA CONSTELAÇÃO FAMILIAR
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'baralho-constelacao-familiar',
    nome: 'Baralho da Constelação Familiar — 250 Cartas Sistêmicas',
    nomeCurto: 'Constelação Familiar',
    categoria: 'Terapia Sistêmica',
    cor: 'sol',
    selo: '250 cartas',
    resumo: '250 cartas sistêmicas, manual e tiragens prontas para conduzir constelações em sessão individual, presencial ou online, sem representantes.',
    publico: ['Consteladoras', 'Terapeutas holísticas', 'Psicólogas sistêmicas', 'Terapeutas integrativas'],
    preco: 37,
    precoDe: 282,
    parcelas: '5x de R$ 8,19',
    checkout: 'https://lastlink.com/p/C6544CFE5/checkout-payment/',
    garantiaDias: 7,
    imagemCapa: IMG_BC + 'kit-completo.webp',
    galeria: [
      IMG_BC + '01-baralho-250-cartas.webp',
      IMG_BC + '02-manual-do-campo.webp',
      IMG_BC + '03-guia-7-tiragens.webp',
      IMG_BC + '04-falas-sistemicas-de-cura.webp',
      IMG_BC + '06-protocolo-pro-terapeuta.webp',
      IMG_BC + 'b01-oraculo-reconciliacao.webp',
    ],
    seo: {
      title: 'Baralho da Constelação Familiar — 250 Cartas Sistêmicas',
      description: '250 cartas sistêmicas, Manual do Campo e 7 tiragens prontas para constelar em sessão individual, presencial ou online. Baseado em Hellinger.',
    },
    hero: {
      eyebrow: 'Baseado nas Ordens do Amor de Hellinger',
      titulo: 'Conduza uma constelação completa em <em>sessão individual</em>, com 250 cartas sistêmicas',
      subtitulo: 'Baralho, Manual do Campo e tiragens prontas para tornar visível a lealdade invisível por trás do padrão que se repete — <strong>sem representantes, sem bonecos, sem grupo</strong>. No presencial, no online ou para o seu próprio processo.',
      bullets: [
        'Acesso imediato por e-mail',
        'Use no celular ou imprima',
        '250 cartas + Manual do Campo',
        'Suporte humano pelo WhatsApp',
      ],
    },
    problema: {
      titulo: 'O mesmo padrão <em>volta</em> — no relacionamento, no dinheiro, na culpa',
      paragrafos: [
        'Seu cliente já fez terapia, meditou, buscou outros caminhos. E o mesmo roteiro se repete: relações que terminam do mesmo jeito, dificuldade com dinheiro, uma culpa que não tem explicação.',
        'Na visão sistêmica de Bert Hellinger, muitos desses padrões podem estar ligados a lealdades invisíveis: por amor, repetimos o destino de alguém que foi excluído ou esquecido no sistema familiar.',
        'O desafio de quem atende é tornar esse movimento visível em uma sessão individual, sem grupo nem representantes, e conduzir até um fechamento que traga paz.',
      ],
      dores: [
        'Dificuldade de constelar sem grupo ou representantes',
        'Baralhos com poucas cartas, que não alcançam padrões específicos',
        'Travar na tiragem sem saber qual pergunta fazer',
        'Não ter as falas certas para fechar o movimento',
        'Atendimento online sem um recurso visual para o campo',
      ],
    },
    solucao: {
      titulo: 'Um <em>mapa</em> do sistema familiar, não um oráculo de frase pronta',
      texto: 'O Baralho da Constelação Familiar tem 250 cartas divididas em 5 grupos que mapeiam o sistema — Vínculo, Excluídos, Ordens, Fala Sistêmica e Prosperidade. Com o Manual do Campo, as tiragens prontas e o banco de falas sistêmicas, você conduz o processo do embaralhar ao fechamento, com um fluxo claro para sessão individual, presencial ou online.',
      pontos: [
        { titulo: 'Mapa mais fino', texto: '250 cartas permitem olhar padrões que baralhos de 40 a 60 cartas não alcançam.' },
        { titulo: 'Tiragens prontas', texto: '7 mapas para as dores mais comuns: relacionamento, dinheiro, mãe, pai, filhos, linhagem e prosperidade.' },
        { titulo: 'Fechamento com fala de honra', texto: 'Frases sistêmicas para encerrar cada movimento com respeito.' },
        { titulo: 'Protocolo para terapeutas', texto: 'Fluxo de condução passo a passo para sessão individual e online.' },
      ],
    },
    entregaveis: [
      { nome: 'Baralho da Constelação Familiar — 250 Cartas', descricao: 'Deck completo em alta resolução, dividido em 5 grupos: Vínculo, Excluídos, Ordens, Fala Sistêmica e Prosperidade.', valor: 97, imagem: IMG_BC + '01-baralho-250-cartas.webp' },
      { nome: 'Manual do Campo', descricao: 'Interpretação carta a carta e o passo a passo fenomenológico, na linha de Hellinger, para tirar, ler e fechar o movimento.', valor: 57, imagem: IMG_BC + '02-manual-do-campo.webp' },
      { nome: 'Guia de 7 Tiragens Prontas', descricao: 'Mapas para Relacionamento, Dinheiro, Mãe, Pai, Filhos, Linhagem Ancestral e Prosperidade.', valor: 37, imagem: IMG_BC + '03-guia-7-tiragens.webp' },
      { nome: 'Falas Sistêmicas de Cura', descricao: 'Banco de frases que fecham cada movimento, como “eu te vejo” e “eu honro, mas sigo meu caminho”.', valor: 27, imagem: IMG_BC + '04-falas-sistemicas-de-cura.webp' },
      { nome: 'Ritual dos 7 Dias', descricao: 'Uma tiragem guiada por dia, durante 7 dias, para olhar um padrão específico sem sobrecarga.', valor: 27, imagem: IMG_BC + '05-ritual-dos-7-dias.webp' },
      { nome: 'Protocolo pro Terapeuta', descricao: 'Como usar o baralho em sessão individual e online, com fluxo de condução passo a passo.', valor: 37, imagem: IMG_BC + '06-protocolo-pro-terapeuta.webp' },
    ],
    bonus: [
      { nome: 'Oráculo da Reconciliação — 65 Cartas de Ho’oponopono', descricao: '65 cartas de Ho’oponopono Familiar e um ritual de perdão ancestral.', valor: 0, imagem: IMG_BC + 'b01-oraculo-reconciliacao.webp' },
      { nome: 'Meditação Guiada de Reconciliação Ancestral (áudio)', descricao: 'Áudio para depois da tiragem, para integrar o movimento.', valor: 0, imagem: IMG_BC + 'b02-meditacao-reconciliacao-ancestral.webp' },
      { nome: 'Guia “Honrar Sem Repetir”', descricao: 'O que fazer na vida prática depois que a carta revela o padrão.', valor: 0, imagem: IMG_BC + 'b03-honrar-sem-repetir.webp' },
      { nome: 'Cartela de Bolso', descricao: 'Versão reduzida e imprimível para consulta rápida.', valor: 0, imagem: IMG_BC + 'b04-cartela-de-bolso.webp' },
      { nome: 'Protocolo de Proteção Energética', descricao: 'Para abrir e fechar cada tiragem com cuidado.', valor: 0, imagem: IMG_BC + 'b05-protecao-energetica.webp' },
    ],
    comoFunciona: [
      'Você finaliza a compra em ambiente seguro.',
      'Recebe no e-mail o acesso ao baralho e a todos os materiais.',
      'Usa as cartas no celular ou imprime o deck completo.',
      'Escolhe uma das 7 tiragens prontas conforme o tema trazido.',
      'Conduz pelo Manual do Campo e fecha com as Falas Sistêmicas.',
    ],
    paraQuem: [
      'Consteladoras que atendem individualmente, sem grupo',
      'Terapeutas holísticas que querem incluir a visão sistêmica',
      'Psicólogas que integram a abordagem sistêmica à prática',
      'Profissionais que atendem online e precisam de um recurso visual',
      'Quem deseja um material estruturado para o próprio autoconhecimento',
    ],
    naoEPara: [
      'Quem busca substituir acompanhamento psicológico, médico ou psiquiátrico',
      'Quem espera um oráculo de “mensagem do dia” ou previsões',
      'Quem procura uma formação ou certificação em constelação familiar',
    ],
    faq: [
      { p: 'O material é físico ou digital?', r: '100% digital, em alta resolução. Você pode imprimir para ter as cartas em mãos ou usar direto na tela do celular.' },
      faqRecebimento,
      faqVitalicio,
      { p: 'Posso usar no atendimento online?', r: 'Sim. O Protocolo pro Terapeuta mostra como conduzir em sessão individual presencial e online, compartilhando as cartas na tela.' },
      { p: 'Preciso já entender de constelação?', r: 'Não. O Manual do Campo explica do zero, na linha das Ordens do Amor. Se você já constela, o baralho acelera e organiza a sua condução.' },
      { p: 'Isso é tarot ou oráculo de frase pronta?', r: 'Não. É um baralho sistêmico baseado nas Ordens do Amor de Hellinger. As cartas ajudam a olhar dinâmicas do sistema familiar; não fazem previsões.' },
      { p: 'Posso usar para mim mesma?', r: 'Pode. O material foi pensado tanto para quem atende quanto para quem deseja olhar o próprio sistema, no seu ritmo. É uma prática integrativa e <strong>não substitui</strong> acompanhamento profissional de saúde.' },
      { p: 'E se eu não gostar?', r: 'Você tem <strong>7 dias de garantia incondicional</strong>. Basta pedir o reembolso ao suporte e devolvemos 100% do valor.' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 5) RADIESTESIA CIGANA
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'radiestesia-cigana',
    nome: 'Kit Radiestesia Cigana',
    nomeCurto: 'Radiestesia Cigana',
    categoria: 'Práticas Integrativas',
    cor: 'roxo',
    selo: 'Kit completo',
    resumo: 'Gráficos, mesa radiônica, fichas e protocolo de tiragem integrada (pêndulo + baralho cigano) prontos para imprimir e usar na próxima sessão.',
    publico: ['Radiestesistas', 'Cartomantes ciganas', 'Terapeutas holísticas', 'Reikianas'],
    preco: 37,
    precoDe: 320,
    parcelas: '5x de R$ 8,19',
    checkout: 'https://lastlink.com/p/C4CF32153/checkout-payment/',
    garantiaDias: 30,
    imagemCapa: IMG_RC + '01-graficos-radiestesicos.webp',
    galeria: [
      IMG_RC + 'kit-completo.webp',
      IMG_RC + '02-mesa-radionica.webp',
      IMG_RC + '03-tiragem-integrada.webp',
      IMG_RC + '04-ficha-diagnostico.webp',
      IMG_RC + '07-ficha-correcao.webp',
      IMG_RC + '09-roteiro-atendimento.webp',
    ],
    seo: {
      title: 'Kit Radiestesia Cigana — Gráficos, Mesa Radiônica e Protocolo',
      description: 'Gráficos radiestésicos, mesa radiônica cigana, fichas e protocolo de pêndulo + baralho cigano. PDF pronto para imprimir, acesso imediato.',
    },
    hero: {
      eyebrow: 'Pêndulo, baralho e mesa radiônica num só método',
      titulo: 'Um atendimento cigano <em>estruturado</em>, do diagnóstico à correção',
      subtitulo: 'Gráficos, mesa radiônica, fichas e protocolo de tiragem integrada prontos para imprimir e usar na próxima sessão. <strong>Acabe com o improviso na cabine</strong> e conduza com clareza e autoridade.',
      bullets: [
        'Acesso imediato por e-mail',
        'PDF pronto para imprimir',
        'Integra com a sua prática atual',
        'Suporte humano pelo WhatsApp',
      ],
    },
    problema: {
      titulo: 'Quando cada sessão depende do <em>improviso</em>',
      paragrafos: [
        'Você já tem o dom, o baralho e o pêndulo. Mas, sem um método, cada atendimento começa do zero: você decide na hora o que perguntar, qual gráfico usar e como encerrar.',
        'O resultado é uma sessão que funciona num dia e trava no outro, uma cliente que não entende o que foi feito e a sensação de estar entregando menos do que poderia.',
        'Um atendimento profissional na linha cigana precisa de estrutura: abrir o campo, investigar a causa, medir, corrigir e registrar.',
      ],
      dores: [
        'Atendimento genérico, sem um fio condutor',
        'Gráficos avulsos que não conversam entre si',
        'Dificuldade de chegar ao que a cliente não verbaliza',
        'Falta de registro para acompanhar a evolução',
        'Insegurança para cobrar mais pela sessão',
      ],
    },
    solucao: {
      titulo: 'Um <em>método</em> cigano completo, pronto para a cabine',
      texto: 'O Kit Radiestesia Cigana une gráficos radiestésicos, mesa radiônica e um protocolo de tiragem integrada em que baralho cigano e pêndulo trabalham juntos. As fichas conduzem cada etapa — diagnóstico, causa, intensidade e correção — e o manual mostra como encaixar tudo num atendimento de 50 minutos. É uma prática integrativa, que soma à sua linha de trabalho sem substituí-la.',
      pontos: [
        { titulo: 'Tiragem integrada', texto: 'Baralho cigano e pêndulo no mesmo passo a passo, do diagnóstico à correção.' },
        { titulo: 'Fichas por etapa', texto: 'Diagnóstico, causa, intensidade e correção registrados de forma organizada.' },
        { titulo: 'Sessão de 50 minutos', texto: 'Roteiro e manual para conduzir sem travar e sem estender demais.' },
        { titulo: 'Identidade cigana', texto: 'Gráficos e mesa criados com a simbologia da linha cigana.' },
      ],
    },
    entregaveis: [
      { nome: 'Gráficos Radiestésicos Ciganos', descricao: 'Gráficos prontos para imprimir, para diagnóstico e correção energética na linha cigana.', valor: 37, imagem: IMG_RC + '01-graficos-radiestesicos.webp' },
      { nome: 'Mesa Radiônica Cigana', descricao: 'Mesa pronta para imprimir e operar, base energética do atendimento.', valor: 27, imagem: IMG_RC + '02-mesa-radionica.webp' },
      { nome: 'Protocolo de Tiragem Integrada (Baralho Cigano + Pêndulo)', descricao: 'Passo a passo que une leitura e radiestesia, do diagnóstico à correção.', valor: 37, imagem: IMG_RC + '03-tiragem-integrada.webp' },
      { nome: 'Ficha de Diagnóstico Cigano', descricao: 'Ficha guiada para mapear o bloqueio com o pêndulo e registrar o que a cliente não verbaliza.', valor: 47, imagem: IMG_RC + '04-ficha-diagnostico.webp' },
      { nome: 'Ficha de Causa Energética', descricao: 'Para investigar a origem do sintoma no campo da cliente.', valor: 27, imagem: IMG_RC + '05-ficha-causa-energetica.webp' },
      { nome: 'Ficha de Intensidade Vibracional', descricao: 'Meça a intensidade do bloqueio nos gráficos e acompanhe a evolução.', valor: 27, imagem: IMG_RC + '06-ficha-intensidade.webp' },
      { nome: 'Ficha de Correção Energética Cigana', descricao: 'Aplicação da correção com os gráficos ciganos e encerramento da sessão.', valor: 47, imagem: IMG_RC + '07-ficha-correcao.webp' },
      { nome: 'Manual de Integração na Sessão', descricao: 'Como encaixar diagnóstico, causa, intensidade e correção num atendimento de 50 minutos.', valor: 37, imagem: IMG_RC + '08-manual-integracao.webp' },
      { nome: 'Roteiro de Atendimento Cigano', descricao: 'Abertura do campo, condução com pêndulo e baralho, perguntas-chave e fechamento.', valor: 17, imagem: IMG_RC + '09-roteiro-atendimento.webp' },
      { nome: 'Checklist de Preparação da Cabine', descricao: 'Intenção, calibração do pêndulo e alinhamento do seu campo antes da sessão.', valor: 17, imagem: IMG_RC + '10-checklist-cabine.webp' },
    ],
    bonus: [
      { nome: 'Áudio de Ativação da Egrégora Cigana', descricao: 'Áudio para você se conectar à força cigana antes de iniciar a sessão.', valor: 0, imagem: IMG_RC + 'b01-audio-ativacao.webp' },
      { nome: '+Gráficos Ciganos Complementares', descricao: 'Coleção extra de gráficos para ampliar o trabalho na cabine.', valor: 0, imagem: IMG_RC + 'b02-graficos-complementares.webp' },
      { nome: '100 Perguntas Ciganas pro Pêndulo', descricao: 'Perguntas prontas por tema: caminhos, amor, prosperidade e proteção.', valor: 0, imagem: IMG_RC + 'b03-100-perguntas.webp' },
      { nome: 'Guia Rápido de Calibração do Pêndulo', descricao: 'Calibre o pêndulo nos gráficos ciganos em poucos minutos, passo a passo.', valor: 0, imagem: IMG_RC + 'b04-guia-calibracao.webp' },
      { nome: 'Planilha de Acompanhamento do Cliente', descricao: 'Registre sessões, evolução energética e observações de cada cliente.', valor: 0, imagem: IMG_RC + 'b05-planilha-acompanhamento.webp' },
    ],
    comoFunciona: [
      'Você finaliza a compra em ambiente seguro.',
      'Recebe no e-mail o acesso a todos os PDFs e ao áudio de ativação.',
      'Imprime os gráficos, a mesa e as fichas.',
      'Calibra o pêndulo com o guia rápido e prepara a cabine pelo checklist.',
      'Conduz a sessão pelo roteiro, do diagnóstico à correção, e registra na planilha.',
    ],
    paraQuem: [
      'Radiestesistas que querem trabalhar com a linha cigana',
      'Cartomantes e tarólogas ciganas que desejam incluir o pêndulo',
      'Terapeutas holísticas (Umbanda, Reiki, xamanismo) que atuam com a força cigana',
      'Quem quer sair do improviso e ter um atendimento estruturado',
      'Profissionais que atendem presencialmente ou a distância',
    ],
    naoEPara: [
      'Quem busca substituir acompanhamento médico ou psicológico',
      'Quem espera resultados garantidos — é uma prática integrativa, não uma promessa',
      'Quem prefere receber material físico pelo correio',
    ],
    faq: [
      { p: 'O kit é físico ou digital?', r: '100% digital, em PDF pronto para imprimir. Você também pode usar no computador, tablet ou celular.' },
      faqRecebimento,
      faqVitalicio,
      { p: 'Posso usar em atendimentos online e presenciais?', r: 'Sim. Use impresso na cabine ou compartilhe a tela no atendimento a distância.' },
      { p: 'Preciso já saber radiestesia?', r: 'Não. O Guia de Calibração do Pêndulo e o Manual de Integração levam você do zero ao uso na sessão. Se você já usa pêndulo e baralho cigano, fica ainda mais rápido.' },
      { p: 'Funciona com a minha prática atual (Umbanda, Reiki, baralho cigano)?', r: 'Sim. O kit foi feito para integrar com o que você já faz, acrescentando a camada de diagnóstico e correção radiestésica.' },
      { p: 'Já tenho gráficos de radiestesia. Vale a pena?', r: 'Sim. O diferencial é o método completo — tiragem integrada, fichas de causa e intensidade e mesa radiônica cigana — que amarra tudo num fluxo de atendimento.' },
      { p: 'E se eu não gostar?', r: 'Você tem <strong>30 dias de garantia</strong>. Basta pedir o reembolso ao suporte e devolvemos 100% do valor.' },
    ],
  },
];
